---
framework: jasmine
licenseTier: xsmall
postMerge:
  pattern:
    - "./test/unit/**/*spec.js"
preMerge:
  pattern:
    - "./test/weex/**/*spec.js"
preRun:
     command:
        - npm install
postRun:
     command:
        - node --version
configFile: "./test/unit/karma.unit.config.js"
version: 2.0

