---
framework: jasmine
licenseTier: xsmall
postMerge:
  pattern:
    - "./test/weex/**/*spec.js"
     - "./test/ssr/**/*spec.js"
preMerge:
  pattern:
    - "./test/weex/**/*spec.js"
preRun:
     command:
        - npm install
postRun:
     command:
        - node --version
version: 2.0


configFile:
    - "./test/weex/jasmine.js"
    - "./test/ssr/jasmine.js"
