---
framework: jasmine
licenseTier: xsmall
postMerge:
  pattern:
    - "./test/ssr/**/*spec.js"
preMerge:
  pattern:
    - "./test/weex/**/*spec.js"
preRun:
     command:
        - npm install
postRun:
     command:
        - node --version
configFile: "./test/ssr/jasmine.js"
version: 2.0

